export const TEMPLATES = {
    EDIT: "SGSG_TEMPLATES_EDIT",
    EDIT_REPLACEMENT: "SGSG_TEMPLATES_EDIT_REPLACEMENT",
    ADD_REPLACEMENT: "SGSG_TEMPLATES_ADD_REPLACEMENT",
    REMOVE_REPLACEMENT: "SGSG_TEMPLATES_REMOVE_REPLACEMENT",
    RESET_REPLACEMENT: "SGSG_TEMPLATES_RESET_REPLACEMENT",
    
    FETCH_REQUEST: {
        INIT_POST: "SGSG_TEMPLATES_FETCH_REQUEST_INIT_POST",
        GET: "SGSG_TEMPLATES_FETCH_REQUEST_GET",
        POST: "SGSG_TEMPLATES_FETCH_REQUEST_POST",
        PUT: "SGSG_TEMPLATES_FETCH_REQUEST_PUT",
        DELETE: "SGSG_TEMPLATES_FETCH_REQUEST_DELETE",
    },
    FETCH_FAIL: {
        GET: "SGSG_TEMPLATES_FETCH_FAIL_GET",
        POST: "SGSG_TEMPLATES_FETCH_FAIL_POST",
        PUT: "SGSG_TEMPLATES_FETCH_FAIL_PUT",
        DELETE: "SGSG_TEMPLATES_FETCH_FAIL_DELETE",
    },
    FETCH_SUCCESS: {
        GET: "SGSG_TEMPLATES_FETCH_SUCCESS_GET",
        GET_ONE: "SGSG_TEMPLATES_FETCH_SUCCESS_GET_ONE",
        POST: "SGSG_TEMPLATES_FETCH_SUCCESS_POST",
        PUT: "SGSG_TEMPLATES_FETCH_SUCCESS_PUT",
    },
    ERROR_RESET: "SGSG_TEMPLATES_ERROR_RESET"
}