export const TEMPLATES = {
  FETCH: "SGSG_TEMPLATES_FETCH",
  POST: "SGSG_TEMPLATES_POST",
  FIX: "SGSG_TEMPLATES_FIX",
  ERROR: "SGSG_TEMPLATES_ERROR",
  REPLACEMENTS: {
    CREATE: "SGSG_REPLACEMENTS_CREATE",
    REMOVE: "SGSG_REPLACEMENTS_REMOVE",
    RESET: "SGSG_REPLACEMENTS_RESET",
    FIX: "SGSG_REPLACEMENTS_FIX",
  }
}