export const TEMPLATES = {
    EDIT: "SGSG_TEMPLATES_EDIT",
    EDIT_REPLACEMENT: "SGSG_TEMPLATES_EDIT_REPLACEMENT",
    ADD_REPLACEMENT: "SGSG_TEMPLATES_ADD_REPLACEMENT",
    REMOVE_REPLACEMENT: "SGSG_TEMPLATES_REMOVE_REPLACEMENT",
    RESET_REPLACEMENT: "SGSG_TEMPLATES_RESET_REPLACEMENT",
    
    FETCH_REQUEST: {
        INIT_POST: "SGSG_TEMPLATES_FETCH_REQUEST_INIT_POST",
        GET: "SGSG_TEMPLATES_FETCH_REQUEST_GET",
        POST: "SGSG_TEMPLATES_FETCH_REQUEST_POST",
        PUT: "SGSG_TEMPLATES_FETCH_REQUEST_PUT",
        DELETE: "SGSG_TEMPLATES_FETCH_REQUEST_DELETE",
    },
    FETCH_FAIL: {
        GET: "SGSG_TEMPLATES_FETCH_FAIL_GET",
        POST: "SGSG_TEMPLATES_FETCH_FAIL_POST",
        PUT: "SGSG_TEMPLATES_FETCH_FAIL_PUT",
        DELETE: "SGSG_TEMPLATES_FETCH_FAIL_DELETE",
    },
    FETCH_SUCCESS: {
        GET: "SGSG_TEMPLATES_FETCH_SUCCESS_GET",
        GET_ONE: "SGSG_TEMPLATES_FETCH_SUCCESS_GET_ONE",
        POST: "SGSG_TEMPLATES_FETCH_SUCCESS_POST",
        PUT: "SGSG_TEMPLATES_FETCH_SUCCESS_PUT",
    },
    ERROR_RESET: "SGSG_TEMPLATES_ERROR_RESET"
}

export const MESSAGES = {
    EDIT_PHONENUM: "SGSG_MESSAGES_EDIT_PHONENUM",
    EDIT_REPLACEMENT: "SGSG_MESSAGES_EDIT_REPLACEMENT",
    SELECT_TEMPLATE: "SGSG_MESSAGES_SELECT_TEMPLATE",
    SEARCH_TEMPLATES: "SGSG_MESSAGES_SEARCH_TEMPLATES",
    ADD_RECEIVERS: "SGSG_MESSAGES_ADD_RECEIVERS",
    REOMVE_RECEIVERS: "SGSG_MESSAGES_REOMVE_RECEIVERS",

    FETCH_REQUEST: {
        GET_TEMPLATES: "SGSG_MESSAGES_FETCH_REQUEST_GET_TEMPLATES",
        POST: "SGSG_MESSAGES_FETCH_REQUEST_POST",
        GET: "SGSG_MESSAGES_FETCH_REQUEST_GET",
        GET_RECEIVERS: "SGSG_MESSAGES_FETCH_REQUEST_GET_RECEIVERS"
    },
    FETCH_SUCCESS: {
        GET_TEMPLATES: "SGSG_MESSAGES_FETCH_SUCCESS_GET_TEMPLATES",
        POST: "SGSG_MESSAGES_FETCH_SUCCESS_POST",
        GET: "SGSG_MESSAGES_FETCH_SUCCESS_GET",
        GET_RECEIVERS: "SGSG_MESSAGES_FETCH_SUCCESS_GET_RECEIVERS"
    },
    FETCH_FAIL: {
        GET_TEMPLATES: "SGSG_MESSAGES_FETCH_FAIL_GET_TEMPLATES",
        POST: "SGSG_MESSAGES_FETCH_FAIL_POST",
        GET: "SGSG_MESSAGES_FETCH_FAIL_GET",
        GET_RECEIVERS: "SGSG_MESSAGES_FETCH_FAIL_GET_RECEIVERS"
    },
    ERROR_RESET: "SGSG_TEMPLATES_ERROR_RESET"
}